# Generated by Django 5.0.4 on 2024-04-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('immatriculation', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiara.personne')),
            ],
        ),
    ]
